config/routes.rb
Rails.application.routes.draw do
  
  
  scope module: :public do
    
    get '/' => "homes#top", as: 'top'
    get '/about' => "homes#about", as: 'about'
    
    resources :items, only: [:index, :show]
    
    delete 'customers/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    
    get '/orders/thanks' => 'orders#thanks', as: 'thanks'
    post '/orders/verification' => 'orders#verification', as: 'verification'
    resources :orders, only: [:new, :create, :index, :show]
    
    get '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    patch '/customers/withdrawal' => 'customers#withdrawal_update', as: 'withdrawal_update'
    resource :customers, only: [:show, :edit, :update]
    
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    
  end
  
  namespace :admin do
    get '/' => "homes#top", as: 'top'
    
    resources :customers, except: [:new, :create, :destroy]
    
    resources :genres, except: [:new, :show, :destroy]
    
    resources :items, except: [:destroy]
  end
 
  
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }
  
  devise_for :customer, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/item.rb
class Item < ApplicationRecord
    
    has_many :cart_items, dependent: :destroy
    has_many :order_items, dependent: :destroy
    belongs_to :genre
    attachment :image
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def index
    @items = Item.all
    
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end



  private
  
  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<h3>商品新規登録</h3>

<%= form_with model: @item, url: admin_item_path(@item), local:true do |f| %>

    <%= f.label :image, "商品画像" %>
    <%= f.attachment_field :image %><br>

    <%= f.label :name, "商品名" %>
    <%= f.text_field :name %><br>

    <%= f.label :introduction, "商品説明" %>
    <%= f.text_area :introduction %><br>

    <%= f.label :genre, "ジャンル" %>
    <%= f.collection_select(:genre_id, @genres, :id, :name) %><br>

    <%= f.label :price, "税抜価格" %>
    <%= f.text_field :price %><br>

    <%= f.label :is_active, "販売ステータス" %>
    <%= f.radio_button :is_active, true, checked: true %>販売中<%= f.radio_button :is_active, false %>販売停止中<br>

    <%= f.submit "変更を保存" %>
    
<% end %>

app/views/admin/items/index.html.erb
<h3>商品一覧</h3>
    <table>
        <thead>
            <tr>
                <th>商品ID</th>
                <th>商品名</th>
                <th>税抜価格</th>
                <th>ジャンル</th>
                <th>ステータス</th>
            </tr>    
        </thead>
        <tbody>
            <% @items.each do |item| %>
                <tr>
                    <td><%= item.id %></td>
                    <td><%= link_to item.name, admin_item_path(item.id) %></td>
                    <td><%= item.price %></td>
                    <td><%= item.genre.name %></td>
                    <td>
                        <% if item.is_active %>
                            販売中
                        <% else %>   
                            販売停止中
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    
    </table>

app/views/admin/items/new.html.erb
<h3>商品新規登録</h3>

<%= form_with model: @item, url:admin_items_path, local:true do |f| %>

    <%= f.label :image, "商品画像" %>
    <%= f.attachment_field :image %><br>

    <%= f.label :name, "商品名" %>
    <%= f.text_field :name %><br>

    <%= f.label :introduction, "商品説明" %>
    <%= f.text_area :introduction %><br>

    <%= f.label :genre, "ジャンル" %>
    <%= f.collection_select(:genre_id, @genres, :id, :name) %><br>

    <%= f.label :price, "税抜価格" %>
    <%= f.text_field :price %><br>

    <%= f.label :is_active, "販売ステータス" %>
    <%= f.radio_button :is_active, true, checked: true %>販売中<%= f.radio_button :is_active, false %>販売停止中<br>

    <%= f.submit "新規登録" %>
    
<% end %>

app/views/admin/items/show.html.erb
<h3>商品詳細</h3>

<%= attachment_image_tag @item, :image, :fill, 180, 90 %>

    <rabel>商品名</rabel>
    <%= @item.name %><br>

    <rabel>商品説明</rabel>
    <%= @item.introduction %><br>
    
    <rabel>ジャンル</rabel>
    <%= @item.genre.name %><br>
    <rabel>税込価格<br>(税抜価格)</rabel>
    <%= "#{(@item.price * 1.08).floor}" + "(#{@item.price})" + "円" %><br>
    <rabel>販売ステータス</rabel>
    <% if @item.is_active %>
      販売中
    <% else %>   
    　販売停止中
    <% end %>

    <%= link_to "編集する", edit_admin_item_path(@item) %>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>