config/routes.rb
Rails.application.routes.draw do
  
  
  scope module: :public do
    
    get '/' => "homes#top", as: 'top'
    get '/about' => "homes#about", as: 'about'
    
    resources :items, only: [:index, :show]
    
    delete 'customers/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    
    get '/orders/thanks' => 'orders#thanks', as: 'thanks'
    post '/orders/verification' => 'orders#verification', as: 'verification'
    resources :orders, only: [:new, :create, :index, :show]
    
    get '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    patch '/customers/withdrawal' => 'customers#withdrawal_update', as: 'withdrawal_update'
    resource :customers, only: [:show, :edit, :update]
    
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    
  end
  
  namespace :admin do
    get '/' => "homes#top", as: 'top'
    
    resources :customers, except: [:new, :create, :destroy]
    
    resources :genres, except: [:new, :show, :destroy]
    
    resources :items, except: [:destroy]
  end
 
  
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }
  
  devise_for :customer, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  def full_name
    self.last_name + self.first_name
    # last_name + first_name
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).reverse_order
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer =  Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path(customer.id)
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h1>Admin::Customers#edit</h1>
<p>Find me in app/views/admin/customers/edit.html.erb</p>

app/views/admin/customers/index.html.erb
<h3>会員一覧</h3>

<table>
    <thead>
        <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
        </tr>
    </thead>
    <tbody>
        <% @customers.each do |customer| %>
            <tr>
                <td><%= customer.id %></td>
                <td><%= link_to "#{customer.last_name + customer.first_name}", admin_customer_path(customer.id) %></td>
                <td><%= customer.email %></td>
                <td>
                    <% if customer.is_active %>
                        有効
                    <% else %>
                        退会
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= paginate @customers %>

app/views/admin/customers/show.html.erb
<h3><%= "#{@customer.last_name}" + "#{@customer.first_name}" %>さんの会員詳細</h3>

<rabel>会員ID</rabel>
<%= @customer.id %>
<br>
<rabel>氏名</rabel>
<%= "#{@customer.last_name}  " + "#{@customer.first_name}" %>
<br>
<rabel>フリガナ</rabel>
<%= "#{@customer.last_name_kana}  " + "#{@customer.first_name_kana}" %>
<br>
<rabel>郵便番号</rabel>
<%= @customer.postal_code %>
<br>
<rabel>住所</rabel>
<%= @customer.address %>
<br>
<rabel>電話番号</rabel>
<%= @customer.telephone_number %>
<br>
<rabel>メールアドレス</rabel>
<%= @customer.email %>
<br>
<rabel>会員ステータス</rabel>
<% if @customer.is_active %>
    有効
<% else %>
    退会
<% end %>
<br>

<%= link_to "編集する", edit_admin_customer_path(@customer) %>
<%= link_to "注文履歴一覧を見る", admin_top_path %>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>