config/routes.rb
Rails.application.routes.draw do
  
  
  scope module: :public do
    
    get '/' => "homes#top", as: 'top'
    get '/about' => "homes#about", as: 'about'
    
    resources :items, only: [:index, :show]
    
    delete 'customers/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    
    get '/orders/thanks' => 'orders#thanks', as: 'thanks'
    post '/orders/verification' => 'orders#verification', as: 'verification'
    resources :orders, only: [:new, :create, :index, :show]
    
    get '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    patch '/customers/withdrawal' => 'customers#withdrawal_update', as: 'withdrawal_update'
    resource :customers, only: [:show, :edit, :update]
    
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    
  end
  
  namespace :admin do
    get '/' => "homes#top", as: 'top'
    
    resources :customers, except: [:new, :create, :destroy]
    
    resources :genres, except: [:new, :show, :destroy]
    
    resources :items, except: [:destroy]
  end
 
  
  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }
  
  devise_for :customer, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    def full_address
        # selfはこのメソッドをよびだしたモノ
        # self.postal_code + self.address + self.name
        "#{postal_code} #{address} #{name}"
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    
    belongs_to :customer
    belongs_to :item
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  def full_name
    self.last_name + self.first_name
    # last_name + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
    
    has_many :items
    
end

app/models/item.rb
class Item < ApplicationRecord
    
    has_many :cart_items, dependent: :destroy
    has_many :order_items, dependent: :destroy
    belongs_to :genre
    attachment :image
end

app/models/order.rb
class Order < ApplicationRecord
    
    has_many :order_items, dependent: :destroy
    belongs_to :customer
    
    enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
    enum status: { 入金待ち: 0, 入金確認: 1, 作成中: 2, 発送準備中: 3, 発送済み: 4 }
    
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    
    belongs_to :item
    belongs_to :order
    
    enum status: { 入金待ち: 0, 入金確認: 1, 作成中: 2, 発送準備中: 3, 発送済み: 4 }
    
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to edit_admin_genre_path(genre.id)
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def index
    @items = Item.all
    
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end



  private
  
  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def configure_permitted_parameters
         devise_parameter_sanitizer.permit(:sign_up, keys: [
        :last_name,
        :first_name, 
        :last_name_kana, 
        :first_name_kana, 
        :postal_code,
        :address,
        :telephone_number,
        :is_active
        ])
    end
    
    def after_sign_in_path_for(resource)
        case resource
        when Admin
            admin_top_path
        when Customer
            top_path
        end
    end
    
    def after_sign_out_path_for(resource)
        #byebug
        case resource
        when :admin
            new_admin_session_path
        when :customer
            top_path
        end
    end
    

    
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
          
        <%= link_to top_path, method: :get do %>
          <i class="fas fa-birthday-cake fa-5x navbar-brand"></i>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="#navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if customer_signed_in? %> 
            <li class=" nav-item mr-5">
              ようこそ、<%= current_customer.last_name %>さん！
            </li>
            <li class="btn btn-outline-secondary nav-item mr-5">
              <%= link_to "マイページ", customers_path %>
            </li>
            <li class="btn btn-outline-secondary nav-item mr-5">
              <%= link_to "商品一覧", items_path %>
            </li>
            <li class="btn btn-outline-secondary nav-item mr-5">
              <%= link_to "カート", cart_items_path %>
            </li>
            <li class="btn btn-outline-secondary nav-item mr-5">
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="btn btn-outline-secondary nav-item mr-5">
              <%= link_to "商品一覧", admin_items_path %>
            </li>
            <li class="btn btn-outline-secondary nav-item mr-5">
              <%= link_to "会員一覧", admin_customers_path %>
            </li>
            <li class="btn btn-outline-secondary nav-item mr-5">
              <%= link_to "注文履歴一覧", admin_top_path %>
            </li>
            <li class="btn btn-outline-secondary nav-item mr-5">
              <%= link_to "ジャンル一覧", admin_genres_path %>
            </li>
            <li class="btn btn-outline-secondary nav-item mr-5">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
            </li>
          <% else %>
            <li class="btn btn-outline-secondary nav-item mr-5">
              <%= link_to "About", about_path %>
            </li>
            <li class="btn btn-outline-secondary nav-item mr-5">
              <%= link_to "商品一覧", items_path %>
            </li>
            <li class="btn btn-outline-secondary nav-item mr-5">
              <%= link_to "新規登録", new_customer_registration_path %>
            </li>
            <li class="btn btn-outline-secondary nav-item mr-5">
              <%= link_to "ログイン", new_customer_session_path %>
            </li class="btn btn-outline-secondary nav-item mr-5">
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
      
    
    <%= yield %>
  </body>
</html>